#include<stdio.h>
#include<conio.h>

void main()
{
int matrices[3][3];
printf("this program will print no.from 1to 9 in matrices form:\n\n");
for(int i=0;i<3;i++)
{
 for(int j=0;j<3;j++)
 {
   printf("enter no.(1-9):");
   scanf("%d",&matrice[i][j]);
   }
   }
   printf("\n\n\n");
   for(int i=0;i<3;i++)
   {
    for (int j=0; j<3;j++)
    {
     printf("%d\t",matrice[i][j]);
     }
     printf("\n");
     }
     printf("\n\n\n so thats the matrice form of no from1-9");
     getch();
     }